---
services:
  nextjs:
    build: prod.Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    # healthcheck:
    #   test: ["CMD", "curl", "-fk", "${FRONTEND_HOSTNAME}:${FRONTEND_PORT}/api/healthcheck"]
    #   interval: 3s
    #   timeout: 3s
    #   retries: 3